/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserFormService } from "../userForm.service";
import { UserFormCreateInput } from "./UserFormCreateInput";
import { UserForm } from "./UserForm";
import { UserFormFindManyArgs } from "./UserFormFindManyArgs";
import { UserFormWhereUniqueInput } from "./UserFormWhereUniqueInput";
import { UserFormUpdateInput } from "./UserFormUpdateInput";

export class UserFormControllerBase {
  constructor(protected readonly service: UserFormService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserForm })
  async createUserForm(
    @common.Body() data: UserFormCreateInput
  ): Promise<UserForm> {
    return await this.service.createUserForm({
      data: data,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        pan: true,
        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [UserForm] })
  @ApiNestedQuery(UserFormFindManyArgs)
  async userForms(@common.Req() request: Request): Promise<UserForm[]> {
    const args = plainToClass(UserFormFindManyArgs, request.query);
    return this.service.userForms({
      ...args,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        pan: true,
        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserForm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async userForm(
    @common.Param() params: UserFormWhereUniqueInput
  ): Promise<UserForm | null> {
    const result = await this.service.userForm({
      where: params,
      select: {
        createdAt: true,
        email: true,
        id: true,
        name: true,
        pan: true,
        phone: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserForm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUserForm(
    @common.Param() params: UserFormWhereUniqueInput,
    @common.Body() data: UserFormUpdateInput
  ): Promise<UserForm | null> {
    try {
      return await this.service.updateUserForm({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          id: true,
          name: true,
          pan: true,
          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserForm })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUserForm(
    @common.Param() params: UserFormWhereUniqueInput
  ): Promise<UserForm | null> {
    try {
      return await this.service.deleteUserForm({
        where: params,
        select: {
          createdAt: true,
          email: true,
          id: true,
          name: true,
          pan: true,
          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
