/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UserForm } from "./UserForm";
import { UserFormCountArgs } from "./UserFormCountArgs";
import { UserFormFindManyArgs } from "./UserFormFindManyArgs";
import { UserFormFindUniqueArgs } from "./UserFormFindUniqueArgs";
import { CreateUserFormArgs } from "./CreateUserFormArgs";
import { UpdateUserFormArgs } from "./UpdateUserFormArgs";
import { DeleteUserFormArgs } from "./DeleteUserFormArgs";
import { UserFormService } from "../userForm.service";
@graphql.Resolver(() => UserForm)
export class UserFormResolverBase {
  constructor(protected readonly service: UserFormService) {}

  async _userFormsMeta(
    @graphql.Args() args: UserFormCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UserForm])
  async userForms(
    @graphql.Args() args: UserFormFindManyArgs
  ): Promise<UserForm[]> {
    return this.service.userForms(args);
  }

  @graphql.Query(() => UserForm, { nullable: true })
  async userForm(
    @graphql.Args() args: UserFormFindUniqueArgs
  ): Promise<UserForm | null> {
    const result = await this.service.userForm(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserForm)
  async createUserForm(
    @graphql.Args() args: CreateUserFormArgs
  ): Promise<UserForm> {
    return await this.service.createUserForm({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => UserForm)
  async updateUserForm(
    @graphql.Args() args: UpdateUserFormArgs
  ): Promise<UserForm | null> {
    try {
      return await this.service.updateUserForm({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UserForm)
  async deleteUserForm(
    @graphql.Args() args: DeleteUserFormArgs
  ): Promise<UserForm | null> {
    try {
      return await this.service.deleteUserForm(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
