/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, UserForm as PrismaUserForm } from "@prisma/client";

export class UserFormServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.UserFormCountArgs, "select">): Promise<number> {
    return this.prisma.userForm.count(args);
  }

  async userForms(
    args: Prisma.UserFormFindManyArgs
  ): Promise<PrismaUserForm[]> {
    return this.prisma.userForm.findMany(args);
  }
  async userForm(
    args: Prisma.UserFormFindUniqueArgs
  ): Promise<PrismaUserForm | null> {
    return this.prisma.userForm.findUnique(args);
  }
  async createUserForm(
    args: Prisma.UserFormCreateArgs
  ): Promise<PrismaUserForm> {
    return this.prisma.userForm.create(args);
  }
  async updateUserForm(
    args: Prisma.UserFormUpdateArgs
  ): Promise<PrismaUserForm> {
    return this.prisma.userForm.update(args);
  }
  async deleteUserForm(
    args: Prisma.UserFormDeleteArgs
  ): Promise<PrismaUserForm> {
    return this.prisma.userForm.delete(args);
  }
}
